/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Novel {
  id: string; // matches slug
  title: string;
  alternativeTitle?: string;
  author: string;
  artist?: string;
  illustrator?: string;
  status: 'ongoing' | 'completed' | 'hiatus' | 'dropped';
  publisher?: string;
  description: string;
  genreIds: string[];
  categoryIds: string[];
  tagIds: string[];
  language: string;
  originalLanguage?: string;
  releaseYear: number;
  rating: number; // average rating
  ratingCount: number;
  ratingSum: number;
  coverUrl?: string;
  bannerUrl?: string;
  slug: string;
  seoTitle?: string;
  seoDescription?: string;
  visibility: 'publish' | 'draft';
  chapterCount: number;
  createdAt: any; // Firestore Timestamp
  updatedAt: any; // Firestore Timestamp
}

export interface Chapter {
  id: string; // novelSlug-chapterNumber or autogenerated
  novelId: string; // references novel id (slug)
  novelTitle: string;
  volume?: string;
  chapterNumber: number;
  title: string;
  content: string; // Rich Text HTML content
  status: 'publish' | 'draft';
  scheduledPublish?: any; // Firestore Timestamp or null
  createdAt: any;
  updatedAt: any;
}

export interface Genre {
  id: string;
  name: string;
  description?: string;
}

export interface Tag {
  id: string;
  name: string;
}

export interface Category {
  id: string;
  name: string;
}

export interface Bookmark {
  id: string; // userId_novelId
  userId: string;
  novelId: string;
  novelTitle: string;
  novelCover?: string;
  createdAt: any;
}

export interface ReadingHistory {
  id: string; // userId_novelId
  userId: string;
  novelId: string;
  novelTitle: string;
  chapterId: string;
  chapterTitle: string;
  chapterNumber: number;
  progress: number; // scroll progress percentage (0-100)
  updatedAt: any;
}

export interface SiteSettings {
  siteName: string;
  siteDescription: string;
  contactEmail: string;
  bannerNotice: string;
  primaryColor?: string;
}
